### ISSUE TITLE
更改repo名字

### ISSUE THREAD

**Issue by TheInterestingSoul** [RomineAdyla/how-to-prosecute-lexburner#1]
据知乎，B站很早就针对 `Lex` 等关键词有屏蔽机制，建议将 `LexBurner` 改为 `zyx（周宇翔）` 等字样

**Comment by Rominez** [comment]
会有这个 issues 大概是打算把这个网址转发到 B 站吧。可是 zyx 对 github 用户就不太友好了呀
另外在 B 站直接搜索 zyx 或者汉字名，也是搜不到结果

**Comment by TheInterestingSoul** [comment]
> 会有这个 issues 大概是打算把这个网址转发到 B 站吧。可是 zyx 对 github 用户就不太友好了呀
> 另外在 B 站直接搜索 zyx 或者汉字名，也是搜不到结果

搜lex可以搜到简介

**Comment by TheInterestingSoul** [comment]
失效关闭

雷蝗嘛，不寒碜

**Comment by RomineAdyla** [comment]
> 失效关闭
> 
> 雷蝗嘛，不寒碜

人都复出了 ........ 净整了些没用的 .........
